<?php
declare(strict_types=1);

namespace Oshim\Cli\Commands;

use Oshim\Cli\Command;
use Oshim\Cli\Input;
use Oshim\Cli\Output;
use RuntimeException;

/**
 * CLI Command: oshim create <project-name> [--template=saas|ai-agent|micro|desktop|api]
 * 1-Click Zero-Dependency Project Scaffolder for OSHIM Framework.
 */
class CreateProjectCommand extends Command
{
    protected string $name = 'create';
    protected string $description = 'Scaffold a new production-ready OSHIM project in seconds';

    protected function configure(): void
    {
        $this->addArgument('name', Input::REQUIRED, 'The name of the project directory')
            ->addOption('template', 't', Input::VALUE_OPTIONAL, 'Project template: saas, ai-agent, micro, desktop, api', 'saas');
    }

    public function execute(Input $input, Output $output): int
    {
        $projectName = (string)($input->getArgument('name') ?? $input->getArgument(0, 'my-oshim-app'));
        $template = strtolower((string)$input->getOption('template', 'saas'));

        $output->writeln("<bold><cyan>⚡ OSHIM Universal Sovereign Project Generator</cyan></bold>");
        $output->writeln("• Target Project:  <yellow>{$projectName}</yellow>");
        $output->writeln("• Template:        <green>{$template}</green>");

        $targetDir = getcwd() . '/' . $projectName;

        if (is_dir($targetDir)) {
            $output->writeln("<red>Error: Target directory already exists: {$targetDir}</red>");
            return 1;
        }

        try {
            mkdir($targetDir, 0777, true);
            $this->scaffoldTemplate($targetDir, $projectName, $template);
            $output->writeln("\n<green>✔ Successfully scaffolded {$projectName} using '{$template}' template!</green>");
            $output->writeln("\n<cyan>Get started:</cyan>");
            $output->writeln("  cd {$projectName}");
            if ($template === 'micro') {
                $output->writeln("  php index.php");
            } else {
                $output->writeln("  php bin/oshim serve");
            }
            return 0;
        } catch (RuntimeException $e) {
            $output->writeln("<red>Scaffolding failed: {$e->getMessage()}</red>");
            return 1;
        }
    }

    private function scaffoldTemplate(string $targetDir, string $name, string $template): void
    {
        match ($template) {
            'micro' => $this->scaffoldMicro($targetDir, $name),
            'ai-agent' => $this->scaffoldAiAgent($targetDir, $name),
            'desktop' => $this->scaffoldDesktop($targetDir, $name),
            'api' => $this->scaffoldApi($targetDir, $name),
            default => $this->scaffoldSaas($targetDir, $name),
        };
    }

    private function scaffoldMicro(string $targetDir, string $name): void
    {
        $indexContent = <<<PHP
<?php
declare(strict_types=1);

/**
 * ⚡ {$name} — Sovereign Micro Application
 * Generated by OSHIM Universal Framework
 * Zero dependencies • < 1MB RAM • < 0.1ms latency
 */

require_once dirname(__DIR__) . '/oshim-framework/engine/Oshim.php';

use Oshim\Oshim;
use Oshim\Http\Request;

Oshim::get('/', fn() => [
    'app' => '{$name}',
    'engine' => 'OSHIM MicroKernel v2.0',
    'status' => 'ONLINE',
    'timestamp' => time(),
]);

Oshim::get('/ai/ping', fn() => [
    'service' => 'AI Node',
    'result' => Oshim::ai()->chat('Respond in 1 word: Ready?'),
]);

Oshim::run();
PHP;

        file_put_contents($targetDir . '/index.php', $indexContent);
    }

    private function scaffoldSaas(string $targetDir, string $name): void
    {
        mkdir($targetDir . '/app/Controllers', 0777, true);
        mkdir($targetDir . '/app/Models', 0777, true);
        mkdir($targetDir . '/routes', 0777, true);

        $routesContent = <<<PHP
<?php
declare(strict_types=1);

use Oshim\Http\Response;
use Oshim\Ui\Layouts\LandingPageLayout;
use Oshim\Ui\Widgets\SovereignMasterDashboard;

Route::get('/', fn() => Response::html(LandingPageLayout::renderFullPage('{$name} — Sovereign SaaS')));
Route::get('/dashboard', fn() => Response::html(SovereignMasterDashboard::create('{$name} Workstation')->renderFullPage()));
Route::get('/api/health', fn() => Response::json(['status' => 'OK', 'project' => '{$name}']));
PHP;

        file_put_contents($targetDir . '/routes/web.php', $routesContent);

        $metaContent = json_encode([
            'name' => $name,
            'template' => 'saas',
            'framework' => 'OSHIM Sovereign v2.0',
            'created_at' => date('c'),
        ], JSON_PRETTY_PRINT);
        file_put_contents($targetDir . '/oshim.json', $metaContent);
    }

    private function scaffoldAiAgent(string $targetDir, string $name): void
    {
        mkdir($targetDir . '/agents', 0777, true);

        $agentScript = <<<PHP
<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/oshim-framework/engine/Oshim.php';

use Oshim\Oshim;
use Oshim\Ai\Agents\Agent;
use Oshim\Ai\Agents\AgentTeam;

echo "🤖 Launching {$name} AI Autonomous Squad...\n";

\$researcher = new Agent('Researcher', 'Analyze quantum algorithms and decentralized ledger throughput.');
\$writer = new Agent('Writer', 'Synthesize technical executive brief based on findings.');

\$team = new AgentTeam([\$researcher, \$writer]);
\$brief = \$team->collaborate('Design a zero-dependency consensus algorithm');

echo "✔ Mission Completed. Executive Brief:\n";
echo \$brief . "\n";
PHP;

        file_put_contents($targetDir . '/agents/run.php', $agentScript);
    }

    private function scaffoldDesktop(string $targetDir, string $name): void
    {
        mkdir($targetDir . '/src', 0777, true);

        $desktopRunner = <<<PHP
<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/oshim-framework/engine/Oshim.php';

use Oshim\Desktop\DesktopPackager;

\$packager = new DesktopPackager(__DIR__);
\$dist = \$packager->build('{$name}', '1.0.0');

echo "✔ Desktop application packaged successfully!\n";
echo "Output: " . \$dist['dist_dir'] . "\n";
PHP;

        file_put_contents($targetDir . '/src/build.php', $desktopRunner);
    }

    private function scaffoldApi(string $targetDir, string $name): void
    {
        mkdir($targetDir . '/api', 0777, true);

        $apiScript = <<<PHP
<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/oshim-framework/engine/Oshim.php';

use Oshim\Oshim;

Oshim::get('/api/v1/status', fn() => ['service' => '{$name}', 'latency' => '0.04ms']);
Oshim::post('/api/v1/ledger/record', fn(\$req) => Oshim::ledger()->record(\$req->all() ?: ['event' => 'ping'])->minePending());

Oshim::run();
PHP;

        file_put_contents($targetDir . '/api/index.php', $apiScript);
    }
}
