<?php
declare(strict_types=1);

namespace Oshim\Dns\Parser;

use Oshim\Dns\Records\RecordType;
use Oshim\Dns\Records\ResourceRecord;
use Oshim\Dns\Zone\Zone;

/**
 * Standard BIND Zone Master File Formatter and Serializer.
 */
class BindZoneSerializer
{
    public static function serialize(Zone $zone): string
    {
        $origin = $zone->getName();
        $ttl = $zone->getDefaultTtl();

        $out = "; BIND Zone File generated by OSHIM DNS Engine\n";
        $out .= "; Zone: {$origin}\n";
        $out .= "; Exported at: " . gmdate('Y-m-d H:i:s') . " UTC\n\n";
        $out .= "\$ORIGIN {$origin}.\n";
        $out .= "\$TTL {$ttl}\n\n";

        // Group 1: SOA
        $soa = $zone->getSoaRecord();
        if ($soa !== null && is_array($soa->getData())) {
            $data = $soa->getData();
            $mname = self::formatDomain($data['mname'] ?? 'ns1.' . $origin, $origin);
            $rname = self::formatDomain($data['rname'] ?? 'hostmaster.' . $origin, $origin);
            $serial = $data['serial'] ?? $zone->getSerial();
            $refresh = $data['refresh'] ?? 3600;
            $retry = $data['retry'] ?? 1800;
            $expire = $data['expire'] ?? 604800;
            $minimum = $data['minimum'] ?? 86400;

            $out .= sprintf(
                "@       IN      SOA     %s %s (\n" .
                "                                %-10d ; Serial\n" .
                "                                %-10d ; Refresh\n" .
                "                                %-10d ; Retry\n" .
                "                                %-10d ; Expire\n" .
                "                                %-10d ; Minimum TTL\n" .
                ")\n\n",
                $mname,
                $rname,
                $serial,
                $refresh,
                $retry,
                $expire,
                $minimum
            );
        }

        // Group 2: NS Records
        foreach ($zone->getRecords() as $r) {
            if ($r->getType() === RecordType::NS) {
                $owner = self::formatOwner($r->getName(), $origin);
                $target = self::formatDomain((string)$r->getData(), $origin);
                $out .= sprintf("%-15s %-7d IN      NS      %s\n", $owner, $r->getTtl(), $target);
            }
        }

        // Group 3: MX Records
        foreach ($zone->getRecords() as $r) {
            if ($r->getType() === RecordType::MX) {
                $owner = self::formatOwner($r->getName(), $origin);
                $data = $r->getData();
                $pref = is_array($data) ? ($data['preference'] ?? 10) : 10;
                $exch = is_array($data) ? ($data['exchange'] ?? '') : (string)$data;
                $out .= sprintf("%-15s %-7d IN      MX      %-5d %s\n", $owner, $r->getTtl(), $pref, self::formatDomain($exch, $origin));
            }
        }

        // Group 4: Address (A, AAAA) & Aliases (CNAME, PTR)
        foreach ($zone->getRecords() as $r) {
            $type = $r->getType();
            if (in_array($type, [RecordType::A, RecordType::AAAA, RecordType::CNAME, RecordType::PTR], true)) {
                $owner = self::formatOwner($r->getName(), $origin);
                $typeName = $r->getTypeName();
                $dataStr = is_scalar($r->getData()) ? (string)$r->getData() : json_encode($r->getData());
                if ($type === RecordType::CNAME || $type === RecordType::PTR) {
                    $dataStr = self::formatDomain($dataStr, $origin);
                }
                $out .= sprintf("%-15s %-7d IN      %-7s %s\n", $owner, $r->getTtl(), $typeName, $dataStr);
            }
        }

        // Group 5: TXT & CAA Records
        foreach ($zone->getRecords() as $r) {
            $type = $r->getType();
            if ($type === RecordType::TXT) {
                $owner = self::formatOwner($r->getName(), $origin);
                $txt = is_scalar($r->getData()) ? (string)$r->getData() : (is_array($r->getData()) ? implode(' ', $r->getData()) : '');
                $out .= sprintf("%-15s %-7d IN      TXT     \"%s\"\n", $owner, $r->getTtl(), addcslashes($txt, '"'));
            } elseif ($type === RecordType::CAA) {
                $owner = self::formatOwner($r->getName(), $origin);
                $data = $r->getData();
                $flags = is_array($data) ? ($data['flags'] ?? 0) : 0;
                $tag = is_array($data) ? ($data['tag'] ?? 'issue') : 'issue';
                $val = is_array($data) ? ($data['value'] ?? '') : '';
                $out .= sprintf("%-15s %-7d IN      CAA     %d %s \"%s\"\n", $owner, $r->getTtl(), $flags, $tag, addcslashes($val, '"'));
            }
        }

        return $out;
    }

    private static function formatOwner(string $name, string $origin): string
    {
        $name = strtolower(trim($name, '.'));
        $origin = strtolower(trim($origin, '.'));

        if ($name === $origin || $name === '@' || $name === '') {
            return '@';
        }

        if (str_ends_with($name, '.' . $origin)) {
            return substr($name, 0, -strlen('.' . $origin));
        }

        return $name;
    }

    private static function formatDomain(string $domain, string $origin): string
    {
        $domain = trim($domain);
        if ($domain === '@' || $domain === '') {
            return '@';
        }
        if (str_ends_with($domain, '.')) {
            return $domain;
        }
        return $domain . '.';
    }
}
